### ISSUE TITLE
Problem with dataset.json

### ISSUE THREAD

**Issue by DaryaMarkova** [sethuiyer/Image-to-Image-search#1]
Could you please tell me where should I take dataset.json from? What is this file? I can't find out it nowhere

**Comment by sethuiyer** [comment]
the dataset.json is a part of Flickr-8K data which has the information about the images present in Flickr-8K dataset.

[Here](https://github.com/sethuiyer/Image-to-Image-search/blob/master/index.py#L9) I am loading the dataset.json, extracting the image paths and the corresponding description of the images. If you are using Flickr-8K data as your database, you can find the dataset.json [here](https://forms.illinois.edu/sec/1713398).

If you are using a custom database, just make sure to change the lines 12-14 of index.py with custom image path and their descriptions.

**Comment by chinmaydas96** [comment]
Can you upload a link directly to  dataset.json or can tell how to create dataset.json for custom dataset, the given link for data with lable . I Will very much appreciate it if you upload it. Thanks.

**Comment by sethuiyer** [comment]
I am not allowed to post the direct link to dataset.json as it is against the licensing requirements of Flickr 8K dataset. 

The dataset.json of Flickr8k dataset basically has the information about labels.

[Here](https://github.com/sethuiyer/Image-to-Image-search/blob/master/index.py#L9) I am opening that file and extracting the image path and the caption and adding that to a list of dictionary called actions.

For custom data, you have to add the custom image path and their descriptions in the actions as per the format described in the index.py file.

I will soon add the code for custom indexing as well as code to train your own image captioner.

**Comment by Ashwin1234** [comment]
Can you please tell me how to prepare the dataset.json file as u have mentioned in the repository

**Comment by sethuiyer** [comment]
I have added a FAQ to the README. Please have a look. Thanks!

**Comment by sethuiyer** [comment]
Hi everyone, I have updated the code to work in Python 3 and added a sample dataset.json in the place where it should be and also added a FAQ section which discusses about the dataset.json. Cheers!

**Comment by Ashwin1234** [comment]
Should i have to enter the description for all the images one by one in the
loop as given in the code or is there any other method for creating the
dataset.json file.
