### ISSUE TITLE
Dataset.json

### ISSUE THREAD

**Issue by Ashwin1234** [sethuiyer/Image-to-Image-search#2]
Should i have to enter the description for all the images one by one in the loop as given in the code or is there any other method for creating this file.

**Comment by sethuiyer** [comment]
In the case where you don't have the captions to the image, you must enter them one by one in the loop as given in the code. 

In case you have the caption, then it must be transformed to this format
```python
     img_data['imgurl'] = image
     img_data['description'] = description
    dataset_list.append(img_data)
dataset_json = {}
dataset_json['images'] = dataset_list
```

so that custom index can parse this dictionary and uploads it to the elastic search service.

**Comment by sethuiyer** [comment]
Kindly check the new release where the reliance of dataset.json has been completely eliminated.
