### ISSUE TITLE
parsing the dataset.json

### ISSUE THREAD

**Issue by Ashwin1234** [sethuiyer/Image-to-Image-search#6]
In server.py or index.py
doc = {'id': i, 'imgurl': data['images'][i]['filename'], 'description': data['images'][i]['sentences'][0]['raw'] }
this line is not executing after creating the dataset.json. 
when executed this file it is showing keyerror: 'filename'.

any help would be appreciated

**Comment by sethuiyer** [comment]
Kindly check the new release where the reliance of dataset.json has been completely eliminated.
