### ISSUE TITLE
TypeError: '>' not supported between instances of 'dict' and 'int'

### ISSUE THREAD

**Issue by AhtashamImtiyaz** [sethuiyer/Image-to-Image-search#7]
I am facing an error in /search

builtins.TypeError

TypeError: '>' not supported between instances of 'dict' and 'int'

    TypeError: '>' not supported between instances of 'dict' and 'int'

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

**Comment by sethuiyer** [comment]
This issue is resolved in the recent merge.
